### ISSUE TITLE
Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of undefined

### ISSUE THREAD

**Issue by sinan** [koding/kd-atom#7] opened 2017-03-27 04:27 UTC
1. kd:mounts
2. select mount

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [kd](https://github.com/koding/kd-atom) package 0.1.6

### Stack Trace

Uncaught TypeError: Cannot read property 'webkitMatchesSelector' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:243

TypeError: Cannot read property 'webkitMatchesSelector' of undefined
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:243:26)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at KDController._showTreeView (/Users/sinan/Projects/koding-atom-package/lib/kd-controller.js:64:19)
    at /Users/sinan/Projects/koding-atom-package/lib/kd-controller.js:127:12
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at MountSelector.confirmed (/Users/sinan/Projects/koding-atom-package/lib/views/mount-selector.js:23:18)
    at MountSelector.module.exports.SelectListView.confirmSelection (/Users/sinan/Projects/koding-atom-package/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Users/sinan/Projects/koding-atom-package/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:24.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-light-ui)
     -0:20.6.0 command-palette:toggle (div.panels)
  4x -0:19.6.0 core:backspace (input.hidden-input)
     -0:16.9.0 editor:consolidate-selections (input.hidden-input)
     -0:16.9.0 core:cancel (input.hidden-input)
     -0:07.5.0 command-palette:toggle (div.panels)
     -0:06.5.0 core:confirm (input.hidden-input)
     -0:06.5.0 kd:mounts (div.panels)
     -0:05.4.0 core:confirm (input.hidden-input)
  2x -0:05.4.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-light-ui)
```

### Non-Core Packages

```
alinement 1.5.0 
atom-beautify 0.29.17 
atom-html-preview 0.1.22 
aurora-theme 1.2.2 
busy-signal 1.3.0 
coffee-compile 0.24.0 
contrast-ui 0.53.0 
daylight-ui 0.2.2 
envy-theme 0.1.1 
es6-javascript 1.0.0 
file-icons 2.1.1 
flexible-ui 0.10.7 
glacier-dark-ui 0.5.0 
highlight-selected 0.13.1 
intentions 1.1.2 
kd 0.1.6 
language-babel 2.57.1 
lint 0.0.1 
linter 2.1.2 
linter-eslint 8.1.4 
linter-ui-default 1.2.1 
min-ui 0.0.4 
numix-ui 0.2.2 
source-preview 0.5.0 
synced-sidebar 0.4.3 
theme-alien-syntax 0.6.0 
toggle-quotes 1.0.1 
tron-theme 0.3.2 
```

**Comment by usirin** [comment] 2017-04-19 12:34
Closing this as i never encountered this problem. 

From the stack trace it seems that it's caused by `_showTreeView` function of `kd-controller`. It's refactored a lot with the recent changes and newly added `try/catch` block over there should catch this error as well.

We can reopen this later, if this occurs again.

**Closed by usirin** 2017-04-19 12:34 UTC
